name: Deploy Bragetools backend to Cloudflare Workers

on: 
  workflow_dispatch:
  push: 
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous redundant deployments
        uses: styfle/cancel-workflow-action@0.9.1
        with: 
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to workers
        working-directory: backend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}