name: Deploy Bragetools backend to Cloudflare Workers

on: 
  workflow_dispatch:
  push: 
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    steps:
      - name: Cancel previous redundant deployments
        uses: styfle/cancel-workflow-action@0.9.1
        with: 
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to workers
        working-directory: backend
        run: npx wrangler deploy --minify src/index.ts